### PR TITLE
Added wait_for_job_completion call to fix bug for clear_foreign_config via ironic cli

### PR DESCRIPTION
**Pull request by mpardhi23**
Hey @cdearborn ,
I have added call for wait_for_job_completion in ironic raid.py to resolve the bug regarding job completion status error occurred while executing clear_foreign_config substep via ironic cli.
I have tested code with the above changes , it was working fine.

I will update the unit test case in same PR , once this code changes is approved by you.

### CODE REVIEW

**Comment by cdearborn** [comment]
Hey Monica, I took a closer look at the code, and I think there needs to be further investigation.  If I understand correctly, the issue is occurring when the delete_configuration cleaning step is being called from the command line.  Is this correct?  If so, then I don't understand why this change is necessary.  This is because the first thing that will occur is the controller reset here:
https://github.com/cdearborn/ironic/blob/master/ironic/drivers/modules/drac/raid.py#L909
Once that happens, the periodic job will wait until that job has finished here:
https://github.com/cdearborn/ironic/blob/master/ironic/drivers/modules/drac/raid.py#L991
Only when that job has finished will the code call into the method for clearing the foreign config here: https://github.com/cdearborn/ironic/blob/master/ironic/drivers/modules/drac/raid.py#L1007
As a result, it shouldn't be necessary to wait for a running job to complete in clear_foreign_config().
Can you investigate further and find out why there is still a pending job when clear_foreign_config is called?

**Review by cdearborn — CHANGES_REQUESTED** [review]
clear_foreign_config should only be called when the reset controller job is finished, so I don't understand why this change is needed.

**Comment by mpardhi23** [comment]
Hi Chris,
Yes correct , the issue is occurring when the delete_configuration cleaning step is being called from the command line. We are facing issue in job completion of clear_foreign_drives, in Drac GUI I have checked job created for clear_foreign_drives and that job is showing completed status and also foreign drives are getting cleared and after that node is stuck in clean_wait state .
So I have checked the ironic-conductor log to verify the job status , there job status for clear_foreign_drives is showing (message='Job in progress.', status='Running', percent_complete='1').
in order to address this issue , we have added wait_for_job_completion call in clear_foreign_drives method.
I will investigate more on this as suggested by you and will update further investigation for the same.

**Comment by cdearborn** [comment]
Closing since this since this is included in Rachit upstream patch.

**Pull request closed without merging**
